import {
  Aperture,
  Camera,
  CloudRain,
  Coffee,
  Contrast,
  Droplet,
  Flame,
  Heart,
  Moon,
  Palette,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Wind,
  Zap,
} from 'lucide-react';

export const FILTERS = [
  { name: 'Normal', value: 'normal', icon: Camera },
  { name: 'Clarendon', value: 'clarendon', icon: Sun },
  { name: 'Gingham', value: 'gingham', icon: Sparkles },
  { name: 'Juno', value: 'juno', icon: Sunset },
  { name: 'Lark', value: 'lark', icon: Sunrise },
  { name: 'Ludwig', value: 'ludwig', icon: Palette },
  { name: 'Valencia', value: 'valencia', icon: Heart },
  { name: 'X-Pro II', value: 'xpro2', icon: Zap },
  { name: 'Aden', value: 'aden', icon: CloudRain },
  { name: 'Brooklyn', value: 'brooklyn', icon: Coffee },
  { name: 'Earlybird', value: 'earlybird', icon: Sunrise },
  { name: 'Inkwell', value: 'inkwell', icon: Moon },
  { name: 'Nashville', value: 'nashville', icon: Star },
  { name: 'Perpetua', value: 'perpetua', icon: Contrast },
  { name: 'Reyes', value: 'reyes', icon: Droplet },
  { name: 'Rise', value: 'rise', icon: Sunrise },
  { name: 'Slumber', value: 'slumber', icon: Moon },
  { name: 'Toaster', value: 'toaster', icon: Flame },
  { name: 'Walden', value: 'walden', icon: Wind },
  { name: 'Willow', value: 'willow', icon: Snowflake },
  { name: 'Vintage', value: 'vintage', icon: Camera },
  { name: 'Cool', value: 'cool', icon: Snowflake },
  { name: 'Warm', value: 'warm', icon: Flame },
  { name: 'Dramatic', value: 'dramatic', icon: Zap },
  { name: 'Vivid', value: 'vivid', icon: Aperture },
] as const;

export const FILTER_STYLES: Record<string, string> = {
  normal: 'none',
  clarendon: 'contrast(1.2) saturate(1.35) brightness(1.1)',
  gingham: 'brightness(1.05) hue-rotate(-10deg)',
  juno: 'contrast(1.2) saturate(1.4) brightness(1.1) sepia(0.2)',
  lark: 'contrast(0.9) saturate(0.85) brightness(1.08)',
  ludwig: 'contrast(1.05) brightness(1.05) saturate(2)',
  valencia: 'contrast(1.08) brightness(1.08) sepia(0.08)',
  xpro2: 'sepia(0.3) contrast(1.3) brightness(0.95) saturate(1.2)',
  aden: 'contrast(0.9) brightness(1.2) saturate(0.85) hue-rotate(-20deg)',
  brooklyn: 'contrast(0.9) brightness(1.1) sepia(0.1)',
  earlybird: 'contrast(0.9) sepia(0.2) brightness(1.1)',
  inkwell: 'grayscale(100%) contrast(1.1) brightness(1.1)',
  nashville: 'sepia(0.2) contrast(1.2) brightness(1.05) saturate(1.2)',
  perpetua: 'contrast(1.1) saturate(1.2)',
  reyes: 'sepia(0.22) brightness(1.1) contrast(0.85) saturate(0.75)',
  rise: 'brightness(1.05) sepia(0.2) contrast(0.9) saturate(0.9)',
  slumber: 'saturate(0.66) brightness(1.05)',
  toaster: 'contrast(1.5) brightness(0.9) sepia(0.1)',
  walden: 'brightness(1.1) hue-rotate(-10deg) sepia(0.3) saturate(1.6)',
  willow: 'grayscale(50%) contrast(0.95) brightness(0.9)',
  vintage: 'sepia(0.5) contrast(1.2) brightness(0.9)',
  cool: 'saturate(1.4) brightness(1.05) hue-rotate(-15deg)',
  warm: 'saturate(1.2) brightness(1.1) hue-rotate(10deg) sepia(0.15)',
  dramatic: 'contrast(1.5) saturate(0.8) brightness(0.95)',
  vivid: 'saturate(1.5) contrast(1.1) brightness(1.05)',
};

export const TEXT_COLORS = [
  '#FFFFFF',
  '#000000',
  '#FF0000',
  '#00FF00',
  '#0000FF',
  '#FFFF00',
  '#FF00FF',
  '#00FFFF',
  '#FF6B6B',
  '#4ECDC4',
  '#45B7D1',
  '#96CEB4',
  '#FFEAA7',
  '#DDA0DD',
  '#98D8C8',
  '#F7DC6F',
] as const;

export const BG_COLORS = [
  'transparent',
  'rgba(0,0,0,0.7)',
  'rgba(255,255,255,0.7)',
  'rgba(255,0,0,0.5)',
  'rgba(0,255,0,0.5)',
  'rgba(0,0,255,0.5)',
  'rgba(255,255,0,0.5)',
  'rgba(255,0,255,0.5)',
] as const;
